[package]
name = "mpi-k8s"
version = "0.1.0"
edition = "2024"

[dependencies]
kube = { version = "3.0.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.27.0", features = ["v1_35"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
bytes = "1"
dashmap = "6"
futures = "0.3"

[build-dependencies]
bindgen = "0.72.1"
pkg-config = "0.3"
