on:
  pull_request: ~
  push:
    branches: [main]

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        # Build dev image, to run the tests in
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: pmi-k8s:dev
          target: dev
          cache-from: type=gha
        # Build final image, to create the pmi-k8s binary
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: pmi-k8s
          cache-from: type=gha
          cache-to: type=gha,mode=max
        # Build test workload
      - uses: docker/build-push-action@v6
        with:
          context: ./tests
          load: true
          tags: pmi-k8s-mpi:test
          cache-from: type=gha,scope=mpi-test
          cache-to: type=gha,mode=max,scope=mpi-test
      - run: |
          kind create cluster --config=./tests/cluster.yaml --kubeconfig=./kubeconfig.yaml
          kind load docker-image pmi-k8s-mpi:test
          yq --inplace '.clusters[0].cluster.server = (.clusters[0].cluster.server | sub("127\.0\.0\.1", "host.docker.internal"))' kubeconfig.yaml
      - run: |
          docker run --rm -i \
            --env KUBECONFIG=/app/pmi-k8s/kubeconfig.yaml \
            --mount type=bind,src=$(pwd),dst=/app/pmi-k8s,ro \
            --mount type=volume,dst=/app/pmi-k8s/target \
            --workdir /app/pmi-k8s \
            pmi-k8s:dev cargo test --features=test-bins
