name: Build & Publish

on:
  pull_request: ~
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  test:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    services:
      registry:
        image: registry:3
        ports: ["5000:5000"]
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      # Build dev image, to run the tests in
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: pmi-k8s:dev
          target: dev
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.arch }}
      # Build final image, which is a dependency of the test image
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: localhost:5000/pmi-k8s
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}
      # Build test image, for k8s tests
      - uses: docker/build-push-action@v6
        with:
          context: ./tests
          load: true
          tags: pmi-k8s-mpi:test
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha,scope=mpi-test-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=mpi-test-${{ matrix.arch }}
          build-contexts: |
            ghcr.io/kwohlfahrt/pmi-k8s=docker-image://localhost:5000/pmi-k8s
      - run: |
          export DOCKER_ADDR=$(ip --json addr show docker0 | yq -r '.[].addr_info[] | select(.family == "inet").local')
          yq --inplace '.networking.apiServerAddress = strenv(DOCKER_ADDR)' ./tests/cluster.yaml
          kind create cluster --config=./tests/cluster.yaml --kubeconfig=./kubeconfig.yaml
          kind load docker-image pmi-k8s-mpi:test
          yq --inplace '.clusters[0].cluster.server = (.clusters[0].cluster.server | sub(strenv(DOCKER_ADDR), "host.docker.internal"))' ./kubeconfig.yaml
      - run: |
          docker run --rm -i \
            --env KUBECONFIG=/app/pmi-k8s/kubeconfig.yaml \
            --mount type=bind,src=$(pwd),dst=/app/pmi-k8s \
            --mount type=volume,dst=/app/pmi-k8s/target \
            --workdir /app/pmi-k8s \
            --add-host=host.docker.internal:host-gateway \
            pmi-k8s:dev cargo test --features=test-bins

  publish:
    needs: [test]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=pr
            type=edge,branch=main
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.0.') }}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      # Build multi-platform image. This should be reasonably efficient due to
      # using the cache from the test stage, but it should be possible to upload
      # image artifacts and simply assemble them here.
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=gha,scope=amd64
            type=gha,scope=arm64
